version: '3'
services:
    redis-server:
        image: 'redis'
        expose: 
            - 6379
    web:
        build: .
        volumes: 
            - .:/var/www/app
        ports:
            - "3000:3000"
        depends_on: 
            - db
        links: 
            - db:db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - "3306:3306"
        environment: 
            # MYSQL_USER: admin
            # MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            # MYSQL_DATABASE: mizmoz