#
# Builder stage.
# This state compile our TypeScript to get the JavaScript code
#
FROM node:latest

ENV PORT=2133
WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
COPY ./src ./src

RUN npm ci --quiet && npm run build

COPY . /usr/src/app

EXPOSE 2133

CMD npm star